// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServerChatWrapper.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tron.Protocol.Wrappers.Server {

  /// <summary>Holder for reflection information generated from ServerChatWrapper.proto</summary>
  public static partial class ServerChatWrapperReflection {

    #region Descriptor
    /// <summary>File descriptor for ServerChatWrapper.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServerChatWrapperReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdTZXJ2ZXJDaGF0V3JhcHBlci5wcm90bxIddHJvbi5wcm90b2NvbC53cmFw",
            "cGVycy5zZXJ2ZXIaCkNoYXQucHJvdG8aD0NvbmZpZ3VyZS5wcm90bxoLUmVh",
            "ZHkucHJvdG8imAIKC0NoYXRXcmFwcGVyEksKDG1lc3NhZ2VfdHlwZRgBIAEo",
            "DjI1LnRyb24ucHJvdG9jb2wud3JhcHBlcnMuc2VydmVyLkNoYXRXcmFwcGVy",
            "TWVzc2FnZVR5cGUSNAoMY2hhdF9tZXNzYWdlGAIgASgLMhwudHJvbi5wcm90",
            "b2NvbC5tZXNzYWdlcy5DaGF0SAASNgoNcmVhZHlfbWVzc2FnZRgDIAEoCzId",
            "LnRyb24ucHJvdG9jb2wubWVzc2FnZXMuUmVhZHlIABI+ChFjb25maWd1cmVf",
            "bWVzc2FnZRgEIAEoCzIhLnRyb24ucHJvdG9jb2wubWVzc2FnZXMuQ29uZmln",
            "dXJlSABCDgoMcmVhbF9tZXNzYWdlKoEBChZDaGF0V3JhcHBlck1lc3NhZ2VU",
            "eXBlEh8KG0NIQVRXUkFQUEVSTUVTU0FHRVRZUEVfQ0hBVBAAEiAKHENIQVRX",
            "UkFQUEVSTUVTU0FHRVRZUEVfUkVBRFkQARIkCiBDSEFUV1JBUFBFUk1FU1NB",
            "R0VUWVBFX0NPTkZJR1VSRRACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Tron.Protocol.Messages.ChatReflection.Descriptor, global::Tron.Protocol.Messages.ConfigureReflection.Descriptor, global::Tron.Protocol.Messages.ReadyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Tron.Protocol.Wrappers.Server.ChatWrapperMessageType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tron.Protocol.Wrappers.Server.ChatWrapper), global::Tron.Protocol.Wrappers.Server.ChatWrapper.Parser, new[]{ "MessageType", "ChatMessage", "ReadyMessage", "ConfigureMessage" }, new[]{ "RealMessage" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ChatWrapperMessageType {
    [pbr::OriginalName("CHATWRAPPERMESSAGETYPE_CHAT")] Chat = 0,
    [pbr::OriginalName("CHATWRAPPERMESSAGETYPE_READY")] Ready = 1,
    [pbr::OriginalName("CHATWRAPPERMESSAGETYPE_CONFIGURE")] Configure = 2,
  }

  #endregion

  #region Messages
  public sealed partial class ChatWrapper : pb::IMessage<ChatWrapper> {
    private static readonly pb::MessageParser<ChatWrapper> _parser = new pb::MessageParser<ChatWrapper>(() => new ChatWrapper());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChatWrapper> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tron.Protocol.Wrappers.Server.ServerChatWrapperReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatWrapper() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatWrapper(ChatWrapper other) : this() {
      messageType_ = other.messageType_;
      switch (other.RealMessageCase) {
        case RealMessageOneofCase.ChatMessage:
          ChatMessage = other.ChatMessage.Clone();
          break;
        case RealMessageOneofCase.ReadyMessage:
          ReadyMessage = other.ReadyMessage.Clone();
          break;
        case RealMessageOneofCase.ConfigureMessage:
          ConfigureMessage = other.ConfigureMessage.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatWrapper Clone() {
      return new ChatWrapper(this);
    }

    /// <summary>Field number for the "message_type" field.</summary>
    public const int MessageTypeFieldNumber = 1;
    private global::Tron.Protocol.Wrappers.Server.ChatWrapperMessageType messageType_ = global::Tron.Protocol.Wrappers.Server.ChatWrapperMessageType.Chat;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Tron.Protocol.Wrappers.Server.ChatWrapperMessageType MessageType {
      get { return messageType_; }
      set {
        messageType_ = value;
      }
    }

    /// <summary>Field number for the "chat_message" field.</summary>
    public const int ChatMessageFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Tron.Protocol.Messages.Chat ChatMessage {
      get { return realMessageCase_ == RealMessageOneofCase.ChatMessage ? (global::Tron.Protocol.Messages.Chat) realMessage_ : null; }
      set {
        realMessage_ = value;
        realMessageCase_ = value == null ? RealMessageOneofCase.None : RealMessageOneofCase.ChatMessage;
      }
    }

    /// <summary>Field number for the "ready_message" field.</summary>
    public const int ReadyMessageFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Tron.Protocol.Messages.Ready ReadyMessage {
      get { return realMessageCase_ == RealMessageOneofCase.ReadyMessage ? (global::Tron.Protocol.Messages.Ready) realMessage_ : null; }
      set {
        realMessage_ = value;
        realMessageCase_ = value == null ? RealMessageOneofCase.None : RealMessageOneofCase.ReadyMessage;
      }
    }

    /// <summary>Field number for the "configure_message" field.</summary>
    public const int ConfigureMessageFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Tron.Protocol.Messages.Configure ConfigureMessage {
      get { return realMessageCase_ == RealMessageOneofCase.ConfigureMessage ? (global::Tron.Protocol.Messages.Configure) realMessage_ : null; }
      set {
        realMessage_ = value;
        realMessageCase_ = value == null ? RealMessageOneofCase.None : RealMessageOneofCase.ConfigureMessage;
      }
    }

    private object realMessage_;
    /// <summary>Enum of possible cases for the "real_message" oneof.</summary>
    public enum RealMessageOneofCase {
      None = 0,
      ChatMessage = 2,
      ReadyMessage = 3,
      ConfigureMessage = 4,
    }
    private RealMessageOneofCase realMessageCase_ = RealMessageOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RealMessageOneofCase RealMessageCase {
      get { return realMessageCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearRealMessage() {
      realMessageCase_ = RealMessageOneofCase.None;
      realMessage_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ChatWrapper);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChatWrapper other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageType != other.MessageType) return false;
      if (!object.Equals(ChatMessage, other.ChatMessage)) return false;
      if (!object.Equals(ReadyMessage, other.ReadyMessage)) return false;
      if (!object.Equals(ConfigureMessage, other.ConfigureMessage)) return false;
      if (RealMessageCase != other.RealMessageCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageType != global::Tron.Protocol.Wrappers.Server.ChatWrapperMessageType.Chat) hash ^= MessageType.GetHashCode();
      if (realMessageCase_ == RealMessageOneofCase.ChatMessage) hash ^= ChatMessage.GetHashCode();
      if (realMessageCase_ == RealMessageOneofCase.ReadyMessage) hash ^= ReadyMessage.GetHashCode();
      if (realMessageCase_ == RealMessageOneofCase.ConfigureMessage) hash ^= ConfigureMessage.GetHashCode();
      hash ^= (int) realMessageCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MessageType != global::Tron.Protocol.Wrappers.Server.ChatWrapperMessageType.Chat) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MessageType);
      }
      if (realMessageCase_ == RealMessageOneofCase.ChatMessage) {
        output.WriteRawTag(18);
        output.WriteMessage(ChatMessage);
      }
      if (realMessageCase_ == RealMessageOneofCase.ReadyMessage) {
        output.WriteRawTag(26);
        output.WriteMessage(ReadyMessage);
      }
      if (realMessageCase_ == RealMessageOneofCase.ConfigureMessage) {
        output.WriteRawTag(34);
        output.WriteMessage(ConfigureMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MessageType != global::Tron.Protocol.Wrappers.Server.ChatWrapperMessageType.Chat) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageType);
      }
      if (realMessageCase_ == RealMessageOneofCase.ChatMessage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatMessage);
      }
      if (realMessageCase_ == RealMessageOneofCase.ReadyMessage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReadyMessage);
      }
      if (realMessageCase_ == RealMessageOneofCase.ConfigureMessage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ConfigureMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChatWrapper other) {
      if (other == null) {
        return;
      }
      if (other.MessageType != global::Tron.Protocol.Wrappers.Server.ChatWrapperMessageType.Chat) {
        MessageType = other.MessageType;
      }
      switch (other.RealMessageCase) {
        case RealMessageOneofCase.ChatMessage:
          if (ChatMessage == null) {
            ChatMessage = new global::Tron.Protocol.Messages.Chat();
          }
          ChatMessage.MergeFrom(other.ChatMessage);
          break;
        case RealMessageOneofCase.ReadyMessage:
          if (ReadyMessage == null) {
            ReadyMessage = new global::Tron.Protocol.Messages.Ready();
          }
          ReadyMessage.MergeFrom(other.ReadyMessage);
          break;
        case RealMessageOneofCase.ConfigureMessage:
          if (ConfigureMessage == null) {
            ConfigureMessage = new global::Tron.Protocol.Messages.Configure();
          }
          ConfigureMessage.MergeFrom(other.ConfigureMessage);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MessageType = (global::Tron.Protocol.Wrappers.Server.ChatWrapperMessageType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Tron.Protocol.Messages.Chat subBuilder = new global::Tron.Protocol.Messages.Chat();
            if (realMessageCase_ == RealMessageOneofCase.ChatMessage) {
              subBuilder.MergeFrom(ChatMessage);
            }
            input.ReadMessage(subBuilder);
            ChatMessage = subBuilder;
            break;
          }
          case 26: {
            global::Tron.Protocol.Messages.Ready subBuilder = new global::Tron.Protocol.Messages.Ready();
            if (realMessageCase_ == RealMessageOneofCase.ReadyMessage) {
              subBuilder.MergeFrom(ReadyMessage);
            }
            input.ReadMessage(subBuilder);
            ReadyMessage = subBuilder;
            break;
          }
          case 34: {
            global::Tron.Protocol.Messages.Configure subBuilder = new global::Tron.Protocol.Messages.Configure();
            if (realMessageCase_ == RealMessageOneofCase.ConfigureMessage) {
              subBuilder.MergeFrom(ConfigureMessage);
            }
            input.ReadMessage(subBuilder);
            ConfigureMessage = subBuilder;
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
